name: Check for new Revanced Patches release
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  check_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run script and save output
        run: |
          python scripts/check_patches.py > latest_revanced_patch.txt

      - name: Upload output
        uses: actions/upload-artifact@main
        with:
          name: latest_revanced_patch
          path: latest_revanced_patch.txt
