name: Check for new Revanced Patches release
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  check_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests    	
      
      - name: Download artifact
        uses: actions/github-script@v6
        continue-on-error: true
        env:
          WORKFLOW_FILENAME: check_newest_revanced_patch.yml
          ARTIFACT_NAME: latest_revanced_patch
          ARTIFACT_FILENAME: latest_revanced_patch.zip
          UNZIP_DIR: old_patch
        with:
          script: |
            const script = require('./scripts/download-previous-artifact')
            await script({github, context, core})      

      - name: Run script and save output
        run: |
          python scripts/check_patches.py > latest_revanced_patch.txt

      - name: Compare with previous output
        id: compare
        run: |
          if [ -f old_patch/latest_revanced_patch.txt ]; then
            diff old_patch/latest_revanced_patch.txt latest_revanced_patch.txt && echo "The patch has not changed." || echo "changed=true" >> $GITHUB_ENV
          else
            echo "This is the first run, so there's no previous patch to compare with."
          fi

      - name: Upload output
        uses: actions/upload-artifact@main
        with:
          name: latest_revanced_patch
          path: latest_revanced_patch.txt

      - name: Trigger build-apk workflow
        if: env.changed == 'true'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-apk.yml
          token: ${{ secrets.PAT }}
